# /**
#  * @file docker-compose.yml
#  * @author Azmi ŞAHİN (azmisahin@outlook.com)
#  * @brief running multi-container Docker applications.
#  * @version 0.1.4
#  * @date 2022-01-01
#  *
#  * @copyright Copyright (c) 2022
#  */
version: '3.8'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile.${CONTAINER}
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 18, 16, 14.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16-bullseye
        # build
        APP_NAME: ${APP_NAME}
        WORK_DIR: ${WORK_DIR}
        BUILD_DIR: ${BUILD_DIR}
        DIST_DIR: ${DIST_DIR}
        # application
      labels:
        com.azmisahin.description: ${APP_NAME}
        com.azmisahin.department: "DEVOPS"
      # stage
      target: ${ENV}
    container_name: ${APP_NAME}-${ENV}-${CONTAINER}
    environment:
      # build
      APP_NAME: ${APP_NAME}
      WORK_DIR: ${WORK_DIR}
      BUILD_DIR: ${BUILD_DIR}
      DIST_DIR: ${DIST_DIR}
      # application

    volumes:
      - ..:/workspace

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  # data service
  data-service:
    container_name: "${DATABASE_SERVICE_NAME}"
    image: postgres:${DATABASE_SERVICE_VERSION}
    ports:
      - "${DATABASE_SERVICE_HOST_PORT}:${DATABASE_SERVICE_APP_PORT}"
    volumes:
      # The location of the folder where Dockers persistent data is stored
      # - "../.postgresql/data:/var/lib/postgresql/data"
      # Startup scripts used to boot the DB [ apis ]
      - "../data/service:/docker-entrypoint-initdb.d"
    environment:
      ENV: ${ENV}
      APP_NAME: ${APP_NAME}
      CONTAINER: ${CONTAINER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      SECRET_KEY: ${SECRET_KEY}

      # postgres sql
      POSTGRES_USER: "${DATABASE_SERVICE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_SERVICE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_SERVICE_CATALOG}"

      # data service
      DATABASE_SERVICE_VENDOR: "${DATABASE_SERVICE_VENDOR}"
      DATABASE_SERVICE_VERSION: "${DATABASE_SERVICE_VERSION}"
      DATABASE_SERVICE_NAME: "${DATABASE_SERVICE_NAME}"
      DATABASE_SERVICE_DOMAIN: "${DATABASE_SERVICE_DOMAIN}"
      DATABASE_SERVICE_HOST_PORT: "${DATABASE_SERVICE_HOST_PORT}"
      DATABASE_SERVICE_APP_PORT: "${DATABASE_SERVICE_APP_PORT}"
      DATABASE_SERVICE_USER: "${DATABASE_SERVICE_USER}"
      DATABASE_SERVICE_PASSWORD: "${DATABASE_SERVICE_PASSWORD}"
      DATABASE_SERVICE_CATALOG: "${DATABASE_SERVICE_CATALOG}"

      # data service ui
      DATABASE_SERVICE_UI_HOST_PORT: "${DATABASE_SERVICE_UI_HOST_PORT}"
      PGADMIN_DEFAULT_EMAIL: "${AUTHORIZED_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${AUTHORIZED_PASSWORD}"

      # data service sql
      DATABASE_SERVICE_CATALOG_SHEMAS: "${DATABASE_SERVICE_CATALOG_SHEMAS}"
      DATABASE_SERVICE_AUTHENTICATION_ROLE: "${DATABASE_SERVICE_AUTHENTICATION_ROLE}"
      DATABASE_SERVICE_ANONYMOUS_ROLE: "${DATABASE_SERVICE_ANONYMOUS_ROLE}"
      DATABASE_SERVICE_USER_ROLE: "${DATABASE_SERVICE_USER_ROLE}"

      # authorization
      AUTHORIZATION_AUDIENCE_VALID: "${AUTHORIZATION_AUDIENCE_VALID}"
      AUTHORIZATION_ISSUER_VALID: "${AUTHORIZATION_ISSUER_VALID}"
      AUTHORIZATION_ROLE_CLAIM_KEY: "${AUTHORIZATION_ROLE_CLAIM_KEY}"
      AUTHORIZATION_SECRET_BASE64: "${AUTHORIZATION_SECRET_BASE64}"
      AUTHORIZATION_SECRET_KEY: "${AUTHORIZATION_SECRET_KEY}"
      AUTHORIZATION_TOKEN_EXPIRATION: "${AUTHORIZATION_TOKEN_EXPIRATION}"
      AUTHORIZATION_TOKEN_REFRES_EXPIRATION: "${AUTHORIZATION_TOKEN_REFRES_EXPIRATION}"

  # data service ui application
  data-service-ui:
    container_name: "${DATABASE_SERVICE_UI_NAME}"
    image: dpage/pgadmin4
    ports:
      - "${DATABASE_SERVICE_UI_HOST_PORT}:${DATABASE_SERVICE_UI_APP_PORT}"
      # volumes:
      # This ensures that the connection information is preloaded into the pgAdmin instance in the container.
      # this volume not loaded in submodule?
      # - "../.module/postgresql/data/service-ui/servers.json:/pgadmin4/servers.json"
    environment:
      # product
      ENV: "${ENV}"

      # data service ui
      PGADMIN_DEFAULT_EMAIL: "${AUTHORIZED_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${AUTHORIZED_PASSWORD}"
    links:
      - "data-service:data-service"
    depends_on:
      - "data-service"

  # web service rest full
  web-service-rest:
    container_name: "${WEB_SERVICE_REST_NAME}"
    image: postgrest/postgrest:${WEB_SERVICE_REST_VERSION}
    ports:
      - "${WEB_SERVICE_REST_HOST_PORT}:${WEB_SERVICE_REST_APP_PORT}"
    environment:
      # product
      ENV: "${ENV}"

      # rest service database connection
      PGRST_DB_URI: ${WEB_SERVICE_REST_DB_URI}
      PGRST_DB_SCHEMA: ${WEB_SERVICE_REST_API_SHEMA}
      PGRST_DB_ANON_ROLE: ${DATABASE_SERVICE_ANONYMOUS_ROLE}
      # rest service role and authorization
      PGRST_ROLE_CLAIM_KEY: "${AUTHORIZATION_ROLE_CLAIM_KEY}"
      PGRST_JWT_AUD: "3${AUTHORIZATION_AUDIENCE_VALID}"
      PGRST_JWT_SECRET: "${AUTHORIZATION_SECRET_KEY}"
      # api specification
      PGRST_OPENAPI_SERVER_PROXY_URI: ${WEB_SERVICE_REST_OPENAPI_SERVER_PROXY_URI}

    links:
      - "data-service:data-service"
    depends_on:
      - "data-service"

  # web service rest ui
  web-service-rest-ui:
    container_name: "${WEB_SERVICE_REST_UI_NAME}"
    image: swaggerapi/swagger-ui
    ports:
      - "${WEB_SERVICE_REST_UI_HOST_PORT}:${WEB_SERVICE_REST_UI_APP_PORT}"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:${WEB_SERVICE_REST_HOST_PORT}/
